---@class hood.Swapchain
---@field width number
---@field height number
---@field present fun(self: hood.Swapchain)
---@field getCurrentTexture fun(self: hood.Swapchain): hood.Texture?
---@field destroy fun(self: hood.Swapchain)
